### ISSUE TITLE
Couldn't load pics/colormap.pcx: No such file or directory

### ISSUE THREAD

**Issue by GreenTeaSip** [Paril/q2pro#133]
I have baseq2 in the same folder as q2pro.exe but it can't seem to load from it.

**Comment by Paril** [comment]
Sorry for the late reply - did we end up fixing this on Discord with you? We had some issues related to automatic base dir discovery that might have been fixed by now

**Comment by GreenTeaSip** [comment]
> Sorry for the late reply - did we end up fixing this on Discord with you? We had some issues related to automatic base dir discovery that might have been fixed by now

Wasn't me. The issue is still present on latest nightly build unfortunately.

**Comment by d10sfan** [comment]
I'm also seeing this happen on Linux. I'm trying to run q2repo (as q2pro) inside the rerelease directory and  then doing:

```
ln -rsf ./gamex86_64.so ./baseq2/gamex86_64.so

LD_LIBRARY_PATH="./:$LD_LIBRARY_PATH" ./q2pro +set basedir ./baseq2 +set libdir ./
```

And I get the same error
